var d = new Date();
console.log(d);
console.log("Date          :",d.getDate());
console.log("Day in Week   :",d.getDay());
console.log("Month         :",d.getMonth());
console.log("Full Year     :",d.getFullYear());
console.log("Hour          :",d.getHours());
console.log("Minutes       :",d.getMinutes());
console.log("Seconds       :",d.getSeconds());
console.log("Milli Seconds :",d.getMilliseconds());